### ISSUE TITLE
npm install carrack and show warning

### ISSUE THREAD

**Issue by azu** [59naga/carrack#2]
Hi, I try to install carrack and see following warning message:

```sh
$ npm install carrack
npm WARN engine carrack@0.0.3: wanted: {"npm":"^3.3.9"} (current: {"node":"4.1.1","npm":"2.14.6"})
```

I think that `engine.npm` is not necessary for library user.

- https://github.com/59naga/carrack/blob/1bb122774edfa801d06f13c2339c918857fff619/package.json#L6-L8

Do you think about this?

**Comment by 59naga** [comment]
Its 3 lines is due to `eslint-config-59naga`. It relies on `npm dedupe`.
Change the format to `eslint-config-airbnb`, there 3 lines to delete.

>
こんばんは、ダウンロードありがとうございます。
その行は`eslint-config-59naga`が原因です。`npm dedupe`に依存しています。
書式を`eslint-config-airbnb`に変更し、そちらの３行は削除します。

**Comment by azu** [comment]
Thanks
